/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'mike' at '3/7/18 3:04 PM' with Gradle 3.2.1
 *
 * @author mike, @date 3/7/18 3:04 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
